### ISSUE TITLE
Doesn't Seem To Work As Intended

### ISSUE THREAD

**Issue by CG-Tespy** [Kiarash-Parvizi/GameLog#1]
I dropped the prefab into my scene, and nothing showed up. Turns out that the Canvas components were disabled, so I enabled them. But even after that, nothing showed up in the prefab despite the development build's log window having a lot to show.

**Comment by Kiarash-Parvizi** [comment]
After you drop the prefab into the scene, a small icon should appear at the bottom of the game screen. Click on it to enable the log window.
